name: ci

on:

  push:
    paths:
      - ".github/workflows/ci.yml"
      - "fpm.toml"
      - "**.f90"
      - "CMakelists.txt"

  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "fpm.toml"
      - "**.f90"
      - "CMakelists.txt"

jobs:

  gnu-cmake-debug:
    name: gnu-cmake-debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: CMake Configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
    - name: Compile
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build

  gnu-cmake-release:
    name: gnu-cmake-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: CMake Configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
    - name: Compile
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build

  gnu-fpm-debug:
    name: gnu-fpm-debug
    runs-on: ubuntu-latest
    steps:
    - uses: fortran-lang/setup-fpm@v5
      with:
        fpm-version: "v0.10.1"
    - uses: actions/checkout@v4
    - name: Compile
      run: fpm build --profile debug
    - name: Test
      run: fpm test --profile debug

  gnu-fpm-release:
    name: gnu-fpm-release
    runs-on: ubuntu-latest
    steps:
    - uses: fortran-lang/setup-fpm@v5
      with:
        fpm-version: "v0.10.1"
    - uses: actions/checkout@v4
    - name: Compile
      run: fpm build --profile release
    - name: Test
      run: fpm test --profile release
