name: ci

on:

  push:
    paths:
      - ".github/workflows/ci.yml"
      - "fpm.toml"
      - "**.f90"

  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "fpm.toml"
      - "**.f90"

env:
  FPM_FFLAGS: -I/usr/include/hdf5/serial
  FPM_LDFLAGS: -L/usr/lib/x86_64-linux-gnu/hdf5/serial

jobs:

  build_and_test_debug_profile:
    name: Build and test in debug mode
    runs-on: ubuntu-latest

    steps:

    - uses: fortran-lang/setup-fpm@v4
      with:
        fpm-version: "v0.6.0"

    - name: Install HDF5
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libhdf5-dev
    - uses: actions/checkout@v2

    - name: Compile
      run: fpm build --profile debug

    - name: Test
      run: fpm test --profile debug

  build_and_test_release_profile:
    name: Build and test in release mode
    runs-on: ubuntu-latest

    steps:

    - uses: fortran-lang/setup-fpm@v4
      with:
        fpm-version: "v0.6.0"

    - name: Install HDF5
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libhdf5-dev
    - uses: actions/checkout@v2

    - name: Compile
      run: fpm build --profile release

    - name: Test
      run: fpm test --profile release
