name: ci

on:

  push:
    paths:
      - ".github/workflows/ci.yml"
      - "fpm.toml"
      - "**.f90"

  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "fpm.toml"
      - "**.f90"

jobs:

  gnu-cmake-debug:
    name: gnu-cmake-debug
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: cmake -DCMAKE_BUILD_TYPE=Debug -DSERIAL=1 . && make
    - name: Test
      run: make test

  gnu-cmake-release:
    name: gnu-cmake-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: cmake -DCMAKE_BUILD_TYPE=Release -DSERIAL=1 . && make
    - name: Test
      run: make test

  gnu-fpm-debug:
    name: gnu-fpm-debug
    runs-on: ubuntu-latest
    steps:
    - uses: fortran-lang/setup-fpm@v5
      with:
        fpm-version: "v0.10.1"
    - uses: actions/checkout@v4
    - name: Compile
      run: fpm build --profile debug
    - name: Test
      run: fpm test --profile debug

  gnu-fpm-release:
    name: gnu-fpm-release
    runs-on: ubuntu-latest
    steps:
    - uses: fortran-lang/setup-fpm@v5
      with:
        fpm-version: "v0.10.1"
    - uses: actions/checkout@v4
    - name: Compile
      run: fpm build --profile release
    - name: Test
      run: fpm test --profile release
